export default {
	extends: [
		'stylelint-config-standard-scss',
		'stylelint-config-clean-order',
	],
	plugins: [
		'@stylistic/stylelint-plugin',
		'@double-great/stylelint-a11y',
		'stylelint-high-performance-animation',
		'stylelint-plugin-defensive-css',
		'stylelint-plugin-logical-css',
	],
	reportDescriptionlessDisables: true,
	reportNeedlessDisables: true,
	rules: {
		'a11y/no-outline-none': true,
		'a11y/no-text-align-justify': true,
		'alpha-value-notation': 'number',
		'at-rule-disallowed-list': [
			'debug',
			'import',
		],
		'at-rule-empty-line-before': [
			'always',
			{
				except: [
					'blockless-after-same-name-blockless',
					'blockless-after-blockless',
					'first-nested',
				],
				ignoreAtRules: ['else'],
			},
		],
		'at-rule-no-unknown': null,
		'at-rule-no-vendor-prefix': true,
		'at-rule-property-required-list': {
			'font-face': [
				'font-family',
				'font-style',
			],
		},
		'block-no-empty': true,
		'color-function-notation': 'modern',
		'color-named': [
			'never',
			{
				ignore: [
					'inside-function',
				],
			},
		],
		'color-no-hex': true,
		'color-no-invalid-hex': true,
		'custom-property-pattern': null,
		'declaration-block-no-duplicate-properties': true,
		'declaration-block-no-redundant-longhand-properties': [
			true,
			{
				ignoreShorthands: [
					'flex',
					'flex-flow',
					'font',
					'inset',
					'grid',
					'grid-area',
					'grid-column',
					'grid-gap',
					'grid-row',
					'grid-template',
				],
			},
		],
		'declaration-block-single-line-max-declarations': 1,
		'declaration-empty-line-before': 'never',
		'defensive-css/no-list-style-none': [
			true,
			{
				fix: true,
			},
		],
		'defensive-css/no-unsafe-clamp-font-size': true,
		'defensive-css/no-unsafe-will-change': true,
		'defensive-css/require-background-repeat': true,
		'declaration-property-value-disallowed-list': {
			'border': [
				'none',
			],
			'border-bottom': [
				'none',
			],
			'border-left': [
				'none',
			],
			'border-right': [
				'none',
			],
			'border-top': [
				'none',
			],
		},
		'defensive-css/require-dynamic-viewport-height': [
			true,
			{
				fix: true,
			},
		],
		'defensive-css/require-focus-visible': true,
		'defensive-css/require-forced-colors-focus': true,
		'font-family-name-quotes': 'always-unless-keyword',
		'function-url-quotes': 'always',
		'keyframes-name-pattern': null,
		'length-zero-no-unit': true,
		'logical-css/require-logical-properties': [
			true,
			{
				fix: true,
			},
		],
		'max-nesting-depth': [
			4,
			{
				ignoreAtRules: [
					'include',
					'media',
					'supports',
				],
			},
		],
		'media-feature-range-notation': null,
		'no-descending-specificity': null,
		'no-duplicate-selectors': true,
		'no-unknown-animations': true,
		'plugin/no-low-performance-animation-properties': [
			true,
			{
				ignore: 'paint-properties',
			},
		],
		'property-no-unknown': [
			true,
			{
				ignoreProperties: [
					'content-visibility',
					'font-path',
				],
			},
		],
		'property-no-vendor-prefix': true,
		'scss/at-extend-no-missing-placeholder': true,
		'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
		'scss/at-else-closing-brace-space-after': 'always-intermediate',
		'scss/at-else-empty-line-before': 'never',
		'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
		'scss/at-if-closing-brace-space-after': 'always-intermediate',
		'scss/at-root-no-redundant': true,
		'scss/at-use-no-redundant-alias': true,
		'scss/block-no-redundant-nesting': true,
		'scss/declaration-nested-properties': 'never',
		'scss/dimension-no-non-numeric-values': true,
		'scss/dollar-variable-no-namespaced-assignment': true,
		'scss/function-calculation-no-interpolation': true,
		'scss/function-color-channel': true,
		'scss/no-duplicate-dollar-variables': [
			true,
			{
				ignoreDefaults: true,
			},
		],
		'scss/no-duplicate-load-rules': true,
		'scss/no-unused-private-members': true,
		'scss/percent-placeholder-pattern': '^[a-z][a-zA-Z0-9]+$',
		'scss/load-no-partial-leading-underscore': true,
		'scss/at-mixin-pattern': null,
		'scss/at-rule-no-unknown': true,
		'scss/declaration-property-value-no-unknown': true,
		'scss/dollar-variable-colon-space-after': 'always',
		'scss/dollar-variable-colon-space-before': 'never',
		'scss/dollar-variable-pattern': null,
		'scss/load-partial-extension': 'never',
		'scss/no-global-function-names': true,
		'scss/selector-no-redundant-nesting-selector': true,
		'selector-attribute-quotes': 'always',
		'selector-class-pattern': null,
		'selector-id-pattern': null,
		'selector-max-compound-selectors': 10,
		'selector-max-id': 3,
		'selector-no-vendor-prefix': true,
		'selector-not-notation': 'simple',
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-element-no-unknown': true,
		'shorthand-property-no-redundant-values': true,
		'@stylistic/at-rule-name-case': 'lower',
		'@stylistic/block-closing-brace-empty-line-before': 'never',
		'@stylistic/block-closing-brace-newline-after': [
			'always',
			{
				ignoreAtRules: [
					'if',
					'else',
				],
			},
		],
		'@stylistic/block-opening-brace-newline-after': 'always',
		'@stylistic/block-opening-brace-space-before': 'always',
		'@stylistic/color-hex-case': 'lower',
		'@stylistic/declaration-bang-space-after': 'never',
		'@stylistic/declaration-bang-space-before': 'always',
		'@stylistic/declaration-block-semicolon-newline-after': 'always',
		'@stylistic/declaration-block-semicolon-space-before': 'never',
		'@stylistic/declaration-block-trailing-semicolon': 'always',
		'@stylistic/declaration-colon-space-after': 'always',
		'@stylistic/declaration-colon-space-before': 'never',
		'@stylistic/function-comma-space-after': 'always-single-line',
		'@stylistic/function-comma-space-before': 'never',
		'@stylistic/function-parentheses-space-inside': 'never-single-line',
		'@stylistic/function-whitespace-after': 'always',
		'@stylistic/indentation': 'tab',
		'@stylistic/linebreaks': 'unix',
		'@stylistic/max-empty-lines': 1,
		'@stylistic/media-feature-colon-space-after': 'always',
		'@stylistic/media-feature-colon-space-before': 'never',
		'@stylistic/media-feature-name-case': 'lower',
		'@stylistic/media-feature-parentheses-space-inside': 'never',
		'@stylistic/media-feature-range-operator-space-after': 'always',
		'@stylistic/media-feature-range-operator-space-before': 'always',
		'@stylistic/media-query-list-comma-space-after': 'always-single-line',
		'@stylistic/media-query-list-comma-space-before': 'never',
		'@stylistic/named-grid-areas-alignment': true,
		'@stylistic/no-empty-first-line': true,
		'@stylistic/no-eol-whitespace': [
			true,
			{
				severity: 'warning',
			},
		],
		'@stylistic/declaration-colon-newline-after': null,
		'@stylistic/no-extra-semicolons': true,
		'@stylistic/no-missing-end-of-source-newline': true,
		'@stylistic/no-multiple-whitespaces': true,
		'@stylistic/number-leading-zero': 'always',
		'@stylistic/number-no-trailing-zeros': true,
		'@stylistic/property-case': 'lower',
		'@stylistic/selector-attribute-brackets-space-inside': 'never',
		'@stylistic/selector-attribute-operator-space-after': 'never',
		'@stylistic/selector-attribute-operator-space-before': 'never',
		'@stylistic/selector-combinator-space-after': 'always',
		'@stylistic/selector-combinator-space-before': 'always',
		'@stylistic/selector-descendant-combinator-no-non-space': true,
		'@stylistic/selector-max-empty-lines': 0,
		'@stylistic/selector-list-comma-newline-after': 'always',
		'@stylistic/selector-pseudo-class-case': 'lower',
		'@stylistic/selector-pseudo-element-case': 'lower',
		'@stylistic/string-quotes': 'single',
		'@stylistic/unicode-bom': 'never',
		'@stylistic/unit-case': 'lower',
		'@stylistic/value-list-comma-space-after': 'always-single-line',
		'@stylistic/value-list-comma-space-before': 'never',
		'unit-allowed-list': [
			'%',
			'deg',
			'dpi',
			'em',
			'fr',
			'ms',
			'rem',
			's',
			'turn',
			'vh',
			'vmax',
			'vmin',
			'vw',
			'dvh',
			'dvw',
			'cqw',
			'cqh',
			'cqi',
			'cqb',
			'cqmin',
			'cqmax',
			'ch',
			'lh',
			'svh',
			'lvh',
			'dvb',
			'dvi',
			'vi',
			'vb',
		],
		'value-keyword-case': null,
		'value-no-vendor-prefix': true,
	},
	overrides: [
		{
			files: ['**/_root.scss'],
			rules: {
				'color-no-hex': null, // Disable this rule
				'custom-property-empty-line-before': null, // Disable this rule
			},
		},
	],
};
